# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NKrIQmSELvq-f-8x1IY0CNenvp9nv1lU
"""

import cv2

rasm_nomi = input("Rasm nomini kiriting (masalan, rasm.jpg): ")

import cv2
import matplotlib.pyplot as plt


image_path = "16.webp"
image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

edges = cv2.Canny(image, threshold1=100, threshold2=200)

plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(image, cmap="gray")
plt.title("Asl Tasvir")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(edges, cmap="gray")
plt.title("Aniqlangan Chetlar")
plt.axis("off")

plt.tight_layout()
plt.show()